#!/usr/bin/env bash
# This script is displaying the content of the /etc/passwd
# Your script should only display username, user id and home directory
# path for the user
exec < /etc/passwd
while read -r passwd_output; do
	echo "$passwd_output" | cut -d ":" -f1,3,6
done
